apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyI1MjQzOTAyOTEzNDUuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdzLmNvbS90b2RvYXBwLWdydXBvMzpsYXRlc3QiOnsidXNlcm5hbWUiOiJBV1MiLCJwYXNzd29yZCI6ImV5SndZWGxzYjJGa0lqb2lPRXQzWVROSWNGcFpRazVCZUdoeFptZHllV1ZPVjBGcE4wWTFXVGh2Vm1WRmRHTlRTWEpoWVVWM1dIQmlabWwwY0VsMGRGcDRUbU5EZW5WWFFrSm9NRzlaUzFKR1dXOXhRVkU1YVN0TWRISkpWbWx5TjFWdFJtOVpSMDlRVFV4Uk1VMW1NMUlyZG14dGNucFdhMUZPUVUxVmFEUldORk5uV2xWamMzVm5PRVptY3pCUVlUaGlTR1JITUhoaFRYcFpUVTlrVVhoR2FFUjNTbGhtYjA1NFptVnJkMnBKUkd3M2NVbFhaVlV2TmtGbFNtWTNObVJOYlZSeWRqVlBWR04yUm01c1ZVWndWbGRFUlN0MmVFOWlXV3g0UW1FdlptNWFha292VFhCaGRVMHJaeTlxWkcxUkwydDJSRXhQVnpWM1UweHJhbTUwZWtnM1JuUlRSM2R5WlZaVk1uQmFiVE5sTld3NWNFRnZhbU01VVZBNVUyaGpLM1p3VVdsdE0wUTFUMm94WjBSQ2JUVlNTVkJEVlVseFdYWnBOVEJxU0hsRlIwTlllbFY0WXpWRU4zcGhkbXhJVnpkQmVIb3habEZPY2twVVdtdHFibFZKWjJSbGQzUmxhME5LUTFWYVJIY3pZa013UXpSd1Rtb3paMGhxVDNNM1ZFcG5ObmMwY0c4M0wwcFZTVXhWUzJkM05ESkdkbXhLWW13MFRXdDVWMnBDWlRGaE1GQllka3RZYmsxbGJHcG5RVEJDTVVzMU9XdGxaM280V1hVMVQxRlBLMHBPYVVsbE1GaFFlamRpV2tRM1ZGRkpkVkpNUkUxemFqUnJXa2xxTjB4dGVHNUNja012TjJ4Q1V6ZFdjemd4TkVsNVdGaERja0ptUVRKR1QzRnllWEJyVWtGUE1YRTFRbFJ5ZUdJM05tbHVialZxTWtGWFN6azFaVzVKYW1OYVFrRjRTMUZ2VlVGd2FsZFdObkpHVkM5d1JXTjJSa3RsVFZFemFVeE9XbnBvY0dGaGVuRm1Wa2Q1Ym1WRVQxZGpVVFU1YWt0NWJubHNZVU5IWmxGa0x6bFpVRlF4Tmpsak5IaGlaMjFFVG5KemNWVlJjMlEzTW5oemVXcGtPRGhZWm05MVpuVjVaVlJFVG10UGEwVktPRU50WmtOTGJreFFSMmN6T0ZGQ1JrdEpLekpUZVN0V2VIUlJaV3hCVjJjM1NVcHVSa0pHU0dRNVp6UlZWbTlYWmpCaWNpODJZazV6Umk4MUsyZE9MM3BHTUV4UVUwVTRhV0p6UmpSVlMwUTVORWxRYkRkNE5rNW1TbXhtTTBkMGNWQkJSMVpLVmpaU2VWZEdORGRaTTJoTlFXWjRTRUY2UjBJdmRVTXhja1F3UVdScFRHNW5PV05JVm05V2VHRlVkMWRHVFdwWGRFMHdXVlkyYWtGcUwwMVVZelFyV2l0eFVsWndibk15VHpCaE9IWjBNa05KUVc1WGRGWlhWVXBFUmpSR1NraDVTVXhHYjAxNWIzWXZWWGxVYWxnNFVXWkhZMDlHV2s5T2QwTTVlRTlCVW5OQmRVSjFTVE53V21GcFdWWm9URlp2TXpneWQxcG9VSFIyVkUxNFYwSnBRVnA1YTA1cWFURnVaVU53ZW5OQlkzWnBOa2wxWTFORGFHTlFTVXd5WVU5RGVVOXljV3gzWVVOQ1NIWnVXa0Y2ZVhOWWRVZzFjelZ6YUUxcmFYVTVTbVk1Ym01U2RITnJUbGg1YXpGS1dVSnpVRkF6ZGpZMldreDZRVW93WVhoaE5qSXdRM0pXTjJOV1IwTnhOV2R4U3pONVZsSmFiVFZhZFRORVN6VkhTVFV2WVZaTmR6MDlJaXdpWkdGMFlXdGxlU0k2SWtGUlJVSkJTR2gzYlRCWllVbFRTbVZTZEVwdE5XNHhSeloxY1dWbGExaDFiMWhZVUdVMVZVWmpaVGxTY1Rndk1UUjNRVUZCU0RSM1prRlpTa3R2V2tsb2RtTk9RVkZqUjI5SE9IZGlVVWxDUVVSQ2IwSm5hM0ZvYTJsSE9YY3dRa0ozUlhkSVoxbEtXVWxhU1VGWFZVUkNRVVYxVFVKRlJVUk5jRFZYWld0eFMwVm5jV2RWVUVoalowbENSVWxCTjNaV2ExUlRWR0ZHTm1oRmRXaDZNVFpNVGs5dmFHNTZhMFZaVTJaRFlXOTJhRVY2V0d4d2NtTnJRazUzY0hwTlNHdElURFo0VVVsNE9GWmhObWczZGxreWVVcDVjR2QzWVc1b2NqaHJaalE5SWl3aWRtVnljMmx2YmlJNklqSWlMQ0owZVhCbElqb2lSRUZVUVY5TFJWa2lMQ0psZUhCcGNtRjBhVzl1SWpveE5qazNNek0yTkRnMWZRPT0iLCJhdXRoIjoiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsUFJYUXpXVlJPU1dOR2NGcFJhelZDWlVkb2VGcHRaSGxsVjFaUFZqQkdjRTR3V1RGWFZHaDJWbTFXUm1SSFRsUlRXRXBvV1ZWV00xZElRbWxhYld3d1kwVnNNR1JHY0RSVWJVNUVaVzVXV0ZGclNtOU5SemxhVXpGS1IxZFhPWGhSVmtVMVlWTjBUV1JJU2twV2JXeDVUakZXZEZKdE9WcFNNRGxSVkZWNFVrMVZNVzFOTVVseVpHMTRkR051Y0ZkaE1VWlBVVlV4Vm1GRVVsZE9SazV1VjJ4V2FtTXpWbTVQUlZwdFkzcENVVmxVYUdsVFIxSklUVWhvYUZSWWNGcFVWVGxyVlZob1IyRkZVak5UYkdodFlqQTFORnB0Vm5Ka01uQktVa2QzTTJOVmJGaGFWbFYyVG10R2JGTnRXVE5PYlZKT1lsWlNlV1JxVmxCV1IwNHlVbTAxYzFaVlduZFdiR1JGVWxOME1tVkZPV2xYVjNnMFVXMUZkbHB0TldGaGEyOTJWRmhDYUdSVk1ISmFlVGx4V2tjeFVrd3lkREpTUlhoUVZucFdNMVV3ZUhKaGJUVXdaV3RuTTFKdVVsUlNNMlI1V2xaYVZrMXVRbUZpVkU1c1RsZDNOV05GUm5aaGJVMDFWVlpCTlZVeWFHcExNMXAzVlZkc2RFMHdVVEZVTW05NFdqQlNRMkpVVmxOVFZrSkVWbFZzZUZkWVduQk9WRUp4VTBoc1JsSXdUbGxsYkZZMFdYcFdSVTR6Y0doa2JYaEpWbnBrUW1WSWIzaGFiRVpQWTJ0d1ZWZHRkSEZpYkZaS1dqSlNiR1F6VW14aE1FNUxVVEZXWVZKSVkzcFphMDEzVVhwU2QxUnRiM3BhTUdoeFZETk5NMVpGY0c1T2JtTXdZMGM0TTB3d2NGWlRWWGhXVXpKa00wNUVTa2RrYlhoTFdXMTNNRlJYZERWV01uQkRXbFJHYUUxR1FsbGthM1JaWW1zeGJHSkhjRzVSVkVKRFRWVnpNVTlYZEd4YU0yODBWMWhWTVZReFJsQkxNSEJQWVZWc2JFMUdhRkZsYW1ScFYydFJNMVpHUmtwa1ZrcE5Va1V4ZW1GcVVuSlhhMnh4VGpCNGRHVkhOVU5qYTAxMlRqSjRRMVY2WkZkamVtZDRUa1ZzTlZkR2FFUmphMHB0VVZSS1IxUXpSbmxsV0VKeVZXdEdVRTFZUlRGUmJGSjVaVWRKTTA1dGJIVmlhbFp4VFd0R1dGTjZhekZhVnpWS1lXMU9ZVkZyUmpSVE1VWjJWbFZHZDJGc1pGZE9ia3BIVmtNNWQxSlhUakpTYTNSc1ZGWkZlbUZWZUU5WGJuQnZZMGRHYUdWdVJtMVdhMlExWW0xV1JWUXhaR3BWVkZVMVlXdDBOV0p1YkhOWlZVNUlXbXhHYTB4NmJGcFZSbEY0VG1wc2FrNUlhR2xhTWpGRlZHNUtlbU5XVmxKak1sRXpUVzVvZW1WWGNHdFBSR2haV20wNU1WcHVWalZhVmxKRlZHMTBVR0V3Vmt0UFJVNTBXbXRPVEdKcmVGRlNNbU42VDBaR1ExSnJkRXBMZWtwVVpWTjBWMlZJVWxKYVYzaENWakpqTTFOVmNIVlNhMHBIVTBkUk5WcDZVbFpXYlRsWVdtcENhV05wT0RKWmF6VjZVbWs0TVVzeVpFOU1NM0JIVFVWNFVWVXdWVFJoVjBwNlVtcFNWbE13VVRWT1JXeFJZa1JrTkU1ck5XMVRiWGh0VFRCa01HTldRa0pTTVZwTFZtcGFVMlZXWkVkT1JHUmFUVEpvVGxGWFdqUlRSVVkyVWpCSmRtUlZUWGhqYTFGM1VWZFNjRlJITlc1UFYwNUpWbTA1VjJWSFJsVmtNV1JIVkZkd1dHUkZNSGRYVmxreVlXdEdjVXd3TVZWWmVsRnlWMmwwZUZWc1duZGliazE1VkhwQ2FFOUlXakJOYTA1S1VWYzFXR1JHV2xoV1ZYQkZVbXBTUjFOcmFEVlRWWGhIWWpBeE5XSXpXWFpXV0d4VllXeG5ORlZYV2toWk1EbEhWMnM1VDJRd1RUVmxSVGxDVlc1T1FtUlZTakZUVkU1M1YyMUdjRmRXV205VVJscDJUWHBuZVdReGNHOVZTRkl5VmtVeE5GWXdTbkJSVm5BMVlUQTFjV0ZVUm5WYVZVNTNaVzVPUWxrelduQk9hMnd4V1RGT1JHRkhUbEZUVlhkNVdWVTVSR1ZWT1hsalYzZ3pXVlZPUTFOSVduVlhhMFkyWlZoT1dXUlZaekZqZWxaNllVVXhjbUZZVlRWVGJWazFZbTAxVTJSSVRuSlViR2cxWVhwR1MxZFZTbnBWUmtGNlpHcFpNbGRyZURaUlZXOTNXVmhvYUU1cVNYZFJNMHBYVGpKT1YxSXdUbmhPVjJSNFUzcE9OVlpzU21GaVZGWmhaRlJPUlZONlZraFRWRlYyV1ZaYVRtUjZNRGxKYVhkcFdrZEdNRmxYZEd4bFUwazJTV3RHVWxKVlNrSlRSMmd6WWxSQ1dsbFZiRlJUYlZaVFpFVndkRTVYTkhoU2Vsb3hZMWRXYkdFeGFERmlNV2haVlVkVk1WWlZXbXBhVkd4VFkxUm5kazFVVWpOUlZVWkNVMFJTTTFwclJscFRhM1IyVjJ0c2IyUnRUazlSVmtacVVqSTVTRTlJWkdsVlZXeERVVlZTUTJJd1NtNWhNMFp2WVRKc1NFOVlZM2RSYTBvelVsaGtTVm94YkV0WFZXeGhVMVZHV0ZaVlVrTlJWVll4VkZWS1JsSlZVazVqUkZaWVdsZDBlRk13Vm01alYyUldWVVZvYWxvd2JFTlNWV3hDVGpOYVYyRXhVbFJXUjBaSFRtMW9SbVJYYURaTlZGcE5WR3M1ZG1GSE5UWmhNRlphVlRKYVJGbFhPVEpoUlZZMlYwZDRkMk50VG5KUmF6VXpZMGh3VGxOSGRFbFVSRm8wVlZWc05FOUdXbWhPYldjelpHeHJlV1ZWY0RWalIyUXpXVmMxYjJOcWFISmFhbEU1U1dsM2FXUnRWbmxqTW14MlltbEpOa2xxU1dsTVEwb3daVmhDYkVscWIybFNSVVpWVVZZNVRGSldhMmxNUTBwc1pVaENjR050UmpCaFZ6bDFTV3B2ZUU1cWF6Tk5lazB5VGtSbk1XWlJQVDA9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
        - name: to-do-app
          image: 524390291345.dkr.ecr.us-east-1.amazonaws.com/todoapp-grupo3:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
        livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5  
---
apiVersion: v1
kind: Service
metadata:
  # Servicio que va a comunicar a los contenedores por su IP
  name: to-do-app-service
spec:
  # Exponer el servicio al mundo exterior
  type: NodePort
  selector:
    app: to-do-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # Puero que se expone al mundo exterior. NOTA: El rango aceptado es entre 30000-32767
      nodePort: 30200