name: PR check
on: 
  - pull_request

jobs:
  pr:
    runs-on: ubuntu-20.04

    steps:
     - name: Checkout
       uses: actions/checkout@v3
    
     - name: Install depencies
       run: |
        npm install
       working-directory: /

    