name: PR check
on: 
  - pull_request

jobs:
  pr:
    runs-on: ubuntu-20.04

    steps:
     - name: Checkout
       uses: actions/checkout@v3
     
     - name: Clear npm cache
       run: npm cache clean --force
       
    
     - name: Install depencies
       run: |
        yarn install 

     - name: Run test
       run: |
        npm test
 


    